//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDR
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyLopHocPhan
    {
        public string MaSinhVien { get; set; }
        public string MaLopHocPhan { get; set; }
        public System.DateTime NgayDangKy { get; set; }
        public Nullable<int> NhomDangKy { get; set; }
    
        public virtual LopHocPhan LopHocPhan { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
