//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDR
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class GiangVien: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiangVien()
        {
            this.LopHocPhans = new HashSet<LopHocPhan>();
        }
        private string _maGiangVien, _hoTen, _email, _hocVi, _tenChuyenNganh, _passwords;
        private int _role;
        public string MaGiangVien
        {
            get => _maGiangVien;
            set
            {
                _maGiangVien = value;
                OnPropertyChanged("MaGiangVien");
            }
        }
        public string HoTen {
            get => _hoTen;
            set
            {
                _hoTen = value;
                OnPropertyChanged("HoTen");
            }
        }
        public string Email {
            get => _email;
            set
            {
                _email = value;
                OnPropertyChanged("Email");
            }
        }
        public string HocVi {
            get => _hocVi;
            set
            {
                _hocVi = value;
                OnPropertyChanged("HocVi");
            }
        }
        public string TenChuyenNganh {
            get => _tenChuyenNganh;
            set
            {
                _tenChuyenNganh = value;
                OnPropertyChanged("TenChuyenNganh");
            }
        }
        public string Passwords {
            get => _passwords;
            set
            {
                _passwords = value;
                OnPropertyChanged("Passwords");
            }
        }
        public int Role
        {
            get => _role;
            set
            {
                _role = value;
                OnPropertyChanged("Role");
            }
        }
    
        public virtual ChuyenNganh ChuyenNganh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHocPhan> LopHocPhans { get; set; }
    }
}
