//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDR
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class MonHoc: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonHoc()
        {
            this.LopHocPhans = new HashSet<LopHocPhan>();
        }
        private string _maMonHoc, _tenMonHoc, _khoa, _maHocPhan, _tenChuyenNganh;
        private int? _soTinChi;
        public string MaMonHoc
        {
            get => _maMonHoc;
            set
            {
                _maMonHoc = value;
                OnPropertyChanged("MaMonHoc");
            }
        }
        public string TenMonHoc {
            get => _tenMonHoc;
            set
            {
                _tenMonHoc = value;
                OnPropertyChanged("TenMonHoc");
            }
        }
        public Nullable<int> SoTinChi {
            get => _soTinChi;
            set
            {
                _soTinChi = value;
                OnPropertyChanged("SoTinChi");
            }
        }
        public string Khoa
        {
            get => _khoa;
            set
            {
                _khoa = value;
                OnPropertyChanged("Khoa");
            }
        }
        public string MaHocPhan {
            get => _maHocPhan;
            set
            {
                _maHocPhan = value;
                OnPropertyChanged("MaHocPhan");
            }
        }
        public string TenChuyenNganh {
            get => _tenChuyenNganh;
            set
            {
                _tenChuyenNganh = value;
                OnPropertyChanged("TenChuyenNganh");
            }
        }
    
        public virtual ChuyenNganh ChuyenNganh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHocPhan> LopHocPhans { get; set; }
    }
}
