//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDR
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class SinhVien : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.DangKyLopHocPhans = new HashSet<DangKyLopHocPhan>();
        }

        private string _maSinhVien, _tenSinhVien, _hoDem, _tenLop;
        public string MaSinhVien
        {
            get => _maSinhVien;
            set
            {
                _maSinhVien = value;
                OnPropertyChanged("MaSinhVien");
            }
        }
        public string TenSinhVien
        {
            get => _tenSinhVien;
            set
            {
                _tenSinhVien = value;
                OnPropertyChanged("TenSinhVien");
            }
        }
        public string HoDem {
            get => _hoDem;
            set
            {
                _hoDem = value;
                OnPropertyChanged("HoDem");
            }
        }
        public string TenLop {
            get => _hoDem;
            set
            {
                _hoDem = value;
                OnPropertyChanged("TenLop");
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DangKyLopHocPhan> DangKyLopHocPhans { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
